### ISSUE TITLE
PerceptualDiff and Python 3.4.1 exception

### ISSUE THREAD

**Issue by denialofself** [bfirsh/needle#38]
Have some prototype tests written using Needle and Python 3.4.1. When the tests run with the default image comparison setting they run fine. When I added PerceptualDiff to the tests, an ugly exception gets thrown coming out of PIL. 

Traceback (most recent call last):
  File "D:\Temp\TestDev\Needle_Tests_Workflow\Needle_Tests_Workflow\Needle_Tests_Workflow.py", line 42, in test_loginPage
    self.assertScreenshot('body', 'body')
  File "D:\Python34\lib\site-packages\needle\cases.py", line 128, in assertScreenshot
    pass
  File "D:\Python34\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "D:\Python34\lib\site-packages\needle\cases.py", line 198, in compareScreenshot
    self.engine.assertSameFiles(output_file, baseline_file, threshold)
  File "D:\Python34\lib\site-packages\needle\engines\perceptualdiff_engine.py", line 16, in assertSameFiles
    width, height = Image.open(open(output_file)).size
  File "D:\Python34\lib\site-packages\PIL\Image.py", line 2255, in open
    prefix = fp.read(16)
  File "D:\Python34\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
nose.proxy.UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 49: character maps to <undefined>

**Comment by acdha** [comment]
It looks like this was fixed in the source last July:

https://github.com/bfirsh/needle/commits/master/needle/engines/perceptualdiff_engine.py

Is it possible that you have a version earlier than 0.2.2 installed?

**Comment by denialofself** [comment]
I've got 0.2.2 installed according to PIP - I initially installed maybe 3 months ago.

**Comment by jphalip** [comment]
It looks like that fix was pushed after the 0.2.2 release, so we'd need to cut a new release. I could do that in the next couple of days unless someone beats me to it :)

**Comment by jphalip** [comment]
I've just released version 0.2.3. Could you please update and check if that fixes it? Thanks!

**Comment by denialofself** [comment]
Will do first thing tomorrow - thanks !

**Comment by denialofself** [comment]
Looks good! Thanks so much for pushing an update that quickly, it is appreciated!

**Comment by jphalip** [comment]
Great, thanks for checking!
