### ISSUE TITLE
Installing with setuptools problem

### ISSUE THREAD

**Issue by ngavrish** [bfirsh/needle#42]
Running needle-0.3/setup.py -q bdist_egg --dist-dir /var/folders/yd/zc63l4vx2bx0_wx6tkqxb7fm0000gn/T/easy_install-s6hft8jc/needle-0.3/egg-dist-tmp-eg_vn_sg
zip_safe flag not set; analyzing archive contents...
needle.__pycache__.cases.cpython-34: module references __file__
needle.__pycache__.driver.cpython-34: module references __file__
Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    packages=['dao', 'ui', 'ui.nosepython', 'ui.data', 'ui.nosepython', 'ui.nosepython.data_driven', 'ui.nosepython.dlp_ui', 'ui.nosepython.model', 'ui.nosepython.flux_capacitor', 'services', 'services.data', 'services.model'],
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/core.py", line 149, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/802619/Envs/test1/lib/python3.4/site-packages/setuptools/command/install.py", line 65, in run
    self.do_egg_install()
  File "/Users/802619/Envs/test1/lib/python3.4/site-packages/setuptools/command/install.py", line 115, in do_egg_install
    cmd.run()
  File "/Users/802619/Envs/test1/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 360, in run
    self.easy_install(spec, not self.no_deps)
  File "/Users/802619/Envs/test1/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 576, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/Users/802619/Envs/test1/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 627, in install_item
    self.process_distribution(spec, dist, deps)
  File "/Users/802619/Envs/test1/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 682, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/Users/802619/Envs/test1/lib/python3.4/site-packages/pkg_resources.py", line 631, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/Users/802619/Envs/test1/lib/python3.4/site-packages/pkg_resources.py", line 871, in best_match
    return self.obtain(req, installer)
  File "/Users/802619/Envs/test1/lib/python3.4/site-packages/pkg_resources.py", line 883, in obtain
    return installer(requirement)
  File "/Users/802619/Envs/test1/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 595, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Users/802619/Envs/test1/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 625, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Users/802619/Envs/test1/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 822, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Users/802619/Envs/test1/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1028, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Users/802619/Envs/test1/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1013, in run_setup
    run_setup(setup_script, args)
  File "/Users/802619/Envs/test1/lib/python3.4/site-packages/setuptools/sandbox.py", line 50, in run_setup
    lambda: execfile(
  File "/Users/802619/Envs/test1/lib/python3.4/site-packages/setuptools/sandbox.py", line 100, in run
    return func()
  File "/Users/802619/Envs/test1/lib/python3.4/site-packages/setuptools/sandbox.py", line 52, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "/Users/802619/Envs/test1/lib/python3.4/site-packages/setuptools/compat.py", line 78, in execfile
    exec(compile(source, fn, 'exec'), globs, locs)
  File "setup.py", line 61, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/core.py", line 149, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/802619/Envs/test1/lib/python3.4/site-packages/setuptools/command/bdist_egg.py", line 203, in run
    os.path.join(archive_root,'EGG-INFO'), self.zip_safe()
  File "/Users/802619/Envs/test1/lib/python3.4/site-packages/setuptools/command/bdist_egg.py", line 239, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/Users/802619/Envs/test1/lib/python3.4/site-packages/setuptools/command/bdist_egg.py", line 347, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/Users/802619/Envs/test1/lib/python3.4/site-packages/setuptools/command/bdist_egg.py", line 381, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)

**Comment by jphalip** [comment]
Thanks for the report. What exact command did you run, and what platform are you using?

I personally couldn't reproduce this issue on my Mac running "pip install needle" with Python 2.7 or 3.4.

**Comment by ngavrish** [comment]
Seems like it's resolved. I saw you reply too late. Sorry

**Comment by jphalip** [comment]
Ok no worries, thanks for confirming!
