### ISSUE TITLE
Can't import cases from needle

### ISSUE THREAD

**Issue by samuraii** [bfirsh/needle#77]
Hello, there is some import problem. I follow step by step tutorial, also this one http://the-creative-tester.github.io/Python-Visual-Regression-Testing/, but the problem is on the import stage.

```ERROR: Failure: ModuleNotFoundError (No module named 'needle.cases'; 'needle' is not a package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\dev\test\env\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "c:\dev\test\env\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "c:\dev\test\env\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "c:\dev\test\env\lib\site-packages\nose\importer.py", line 92, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Python36\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "C:\Python36\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\dev\test\needle.py", line 1, in <module>
    from needle.cases import NeedleTestCase
ModuleNotFoundError: No module named 'needle.cases'; 'needle' is not a package
```

Python 3.6, Windows 10

**Comment by samuraii** [comment]
I have done it once again and it worked
